name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Login no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Construindo e fazendo push da imagem para o DockerHub
        uses: docker/build-push-action@v3
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            lupandrioli/kube-news:latest
            lupandrioli/kube-news:v${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      
      - name: Definindo o kubeconfig
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      
      - name: Fazendo o deploy no Kubernetes na Digital Ocean
        uses: Azure/k8s-deploy@v3.1
        with:
          images: lupandrioli/kube-news:v${{github.run_number}}
          manifests: ./k8s/deployment.yaml     

          
    
